version: 2
jobs:
  build:
    working_directory: ~/monapt
    docker:
      - image: node:boron
    steps:
      - checkout
      - restore_cache:
          key: node-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing JS dependencies
          command: npm install
      - save_cache:
          key: node-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Running tests
          command: npm run test
